password reset quickbyte
UNM-CARC/QuickBytes pull request #177
Opened 2024-05-12 05:37 UTC by rysc3

2024-05-12 05:43 UTC, rysc3 commented
Maybe we should throw the date we last made sure the quickbyte was accurate there? Obviously they can check when the file was last edited but this could more so represent the last date we checked that the instructions actually work, not necessarily edited the file?

2024-05-22 03:56 UTC, rysc3 commented
Changed verbiage to "validated" as discussed in res. support meeting 5/21/24

2024-05-28 22:57 UTC, gmfricke requested changes
Grammar - "in order "

2024-05-28 22:57 UTC, gmfricke commented on logging_in.md
> +In order to use log in to CARC systems and start computing you will need a terminal that can log in to remote systems using Secure Shell (SSH). If you are using a Linux or Mac machine you are in luck
Check grammar here

2024-06-11 23:05 UTC, gmfricke approved these changes

2024-06-11 23:05 UTC, merged