SSH Keys Quickbyte
UNM-CARC/QuickBytes pull request #178
Opened 2024-05-22 04:02 UTC by rysc3

2024-06-13 15:45 UTC, nap23carc approved these changes
This looks good.

2024-07-23 23:15 UTC, gmfricke requested changes
Add a recommendation that users set a password since anyone can use the file to login to any machine they setup with this key. A password only has to be entered once per session with a key manager so is more convenient, but provides security.

2025-03-27 19:38 UTC, gmfricke commented
@Sumaya112000 Please add a recommendation that users set a password on their key for security reasons.

2025-03-27 19:49 UTC, rysc3 commented
lgtm 🚀

2025-03-27 19:50 UTC, gmfricke approved these changes
woot

2025-03-27 19:50 UTC, merged