Haskell Quickbite
UNM-CARC/QuickBytes pull request #179
Opened 2024-05-24 22:27 UTC by rysc3

2024-06-13 17:04 UTC, nap23carc requested changes
When I work through these instructions, 'stack build' errors out complaining "/usr/bin/ld.gold: error: cannot find -lgmp" and won't finish.

2024-06-13 18:10 UTC, nap23carc approved these changes
Strike my last comment about the library error. That was while I was on a compute node. The stack built while on the head node just fine.

2024-07-23 23:19 UTC, gmfricke requested changes
mfricke@hopper:~ $ module load ghcup
mfricke@hopper:~ $ ghcup install ghc 9.10.1
[ Info  ] downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.8.yaml as file /users/mfricke/.ghcup/cache/ghcup-0.0.8.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  454k  100  454k    0     0  1187k      0 --:--:-- --:--:-- --:--:-- 1190k
[ Warn  ] New GHCup version available: 0.1.30.0. To upgrade, run 'ghcup upgrade'
[ Warn  ] New cabal version available. If you want to install this latest version, run 'ghcup install cabal 3.12.1.0'
[ Warn  ] New hls version available. If you want to install this latest version, run 'ghcup install hls 2.9.0.1'
[ Warn  ] New stack version available. If you want to install this latest version, run 'ghcup install stack 2.15.7'
[ Info  ] downloading: https://downloads.haskell.org/~ghc/9.10.1/ghc-9.10.1-x86_64-rocky8-linux.tar.xz as file /users/mfricke/.ghcup/tmp/ghcup-6b3903f56377b69a/ghc-9.10.1-x86_64-rocky8-linux.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: downloads.haskell.org
[ Error ] [GHCup-05841] Download failed: Process "curl" with arguments ["-fL", "-o",
[ ...   ]                                                 "/users/mfricke/.ghcup/tmp/ghcup-6b3903f56377b69a/ghc-9.10.1-x86_64-rocky8-linux.tar.xz.tmp",
[ ...   ]                                                 "https://downloads.haskell.org/~ghc/9.10.1/ghc-9.10.1-x86_64-rocky8-linux.tar.xz"] failed with exit code 6.
[ Error ] Also check the logs in /users/mfricke/.ghcup/logs
mfricke@hopper:~ $ ghcup install ghc
[ Warn  ] New GHCup version available: 0.1.30.0. To upgrade, run 'ghcup upgrade'
[ Warn  ] New ghc version available. If you want to install this latest version, run 'ghcup install ghc 9.10.1'
[ Warn  ] New cabal version available. If you want to install this latest version, run 'ghcup install cabal 3.12.1.0'
[ Warn  ] New hls version available. If you want to install this latest version, run 'ghcup install hls 2.9.0.1'
[ Warn  ] New stack version available. If you want to install this latest version, run 'ghcup install stack 2.15.7'
[ Warn  ] [GHCup-00110] ghc-9.4.8 is already installed; if you really want to reinstall it, you may want to run 'ghcup install ghc --force 9.4.8'

2025-03-27 19:35 UTC, mdunlavy approved these changes

2025-03-27 19:55 UTC, gmfricke approved these changes
??

2025-03-27 19:55 UTC, merged