create new images dir, update spark
UNM-CARC/QuickBytes pull request #185
Opened 2024-06-09 07:11 UTC by rysc3

2024-06-09 07:19 UTC, rysc3 commented
Need to figure out how to make the images show up properly. relative paths work fine locally, but I'm not sure if I need to add absolute paths for them to show up in the browser and/or how the readthedocs thing will effect it.

2024-06-17 16:09 UTC, nap23carc commented
I think for now making the images work is the main priority. We can change things later if we need to with the readthedocs/sphinx template.

2026-06-16 19:37 UTC, gmfricke requested changes
@Graviton28 Update for Easley

2026-06-24 21:42 UTC, gmfricke approved these changes

2026-06-24 21:42 UTC, merged