udpate checking on running jobs quickbyte
UNM-CARC/QuickBytes pull request #187
Opened 2024-06-11 05:02 UTC by rysc3

2024-06-12 22:55 UTC, nap23carc commented on checking_on_running_jobs.md
>  If you would like to check the status of your job, you can use the `qstat` command to do so. Typing `qstat` without any options will output all currently running or queued jobs to your terminal windo
I believe this line with information about using qstat needs to be removed.

2024-06-12 22:56 UTC, nap23carc requested changes
I think line 4 with information about qstat needs to be remove.

2024-10-26 02:29 UTC, alexknigge approved these changes
All the info Ryan put looks good and updates correctly from what the qstat was. MERGE THIS MATTHEW.

2025-03-27 19:32 UTC, mdunlavy approved these changes

2026-06-16 19:40 UTC, gmfricke requested changes
@Graviton28 please update for Easley

2026-06-16 19:59 UTC, gmfricke commented
Superseded by #202

2026-06-16 19:59 UTC, closed without merging