Submitting Jobs Quickbyte
UNM-CARC/QuickBytes pull request #189
Opened 2024-06-18 04:12 UTC by rysc3

2024-10-26 02:24 UTC, alexknigge commented
All that was changed was putting the slurm equivalent commands from qsub. MERGE THIS MATTHEW.

2024-10-26 02:25 UTC, alexknigge approved these changes
All that was changed was putting the slurm equivalent commands from qsub. MERGE THIS MATTHEW.

2026-06-16 19:41 UTC, gmfricke approved these changes

2026-06-16 19:42 UTC, gmfricke requested changes
@Graviton28 Remove the PBS sections since we don't support those anymore

2026-06-16 19:46 UTC, gmfricke commented
superseded by #197

2026-06-16 19:46 UTC, closed without merging