added jupyter notebook file for multi-GPU tutorial
UNM-CARC/QuickBytes pull request #97
Opened 2021-04-21 19:51 UTC by katcosburn

2021-04-27 19:08 UTC, bruzewskis approved these changes
Seems will written and thorough, I didn't notice any issues running through it

2021-04-28 17:14 UTC, gmfricke approved these changes

2021-04-28 17:15 UTC, gmfricke requested changes
Please add link in the readme page (TOC)

2021-04-28 17:22 UTC, gmfricke approved these changes

2021-04-28 17:22 UTC, merged